sonar.projectKey=finanzas-personales
sonar.projectName=finanzas-personales
sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.php

sonar.php.tests.reportPath=storage/test-results/phpunit-report.xml
sonar.php.coverage.reportPaths=storage/test-results/clover.xml
